
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Button StartBtn;
	private global::Gtk.Button StopBtn;
	private global::Gtk.Button ResetBtn;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button IncTempoBtn;
	private global::Gtk.Button DecTempoBtn;
	private global::Gtk.HBox hbox2;
	private global::Gtk.ComboBox UpperMeterCB;
	private global::Gtk.ComboBox LowerMeterCB;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.StartBtn = new global::Gtk.Button ();
		this.StartBtn.CanFocus = true;
		this.StartBtn.Name = "StartBtn";
		this.StartBtn.UseUnderline = true;
		this.StartBtn.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.vbox1.Add (this.StartBtn);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.StartBtn]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.StopBtn = new global::Gtk.Button ();
		this.StopBtn.CanFocus = true;
		this.StopBtn.Name = "StopBtn";
		this.StopBtn.UseUnderline = true;
		this.StopBtn.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		this.vbox1.Add (this.StopBtn);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.StopBtn]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.ResetBtn = new global::Gtk.Button ();
		this.ResetBtn.CanFocus = true;
		this.ResetBtn.Name = "ResetBtn";
		this.ResetBtn.UseUnderline = true;
		this.ResetBtn.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.vbox1.Add (this.ResetBtn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ResetBtn]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.HeightRequest = 70;
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.IncTempoBtn = new global::Gtk.Button ();
		this.IncTempoBtn.CanFocus = true;
		this.IncTempoBtn.Name = "IncTempoBtn";
		this.IncTempoBtn.UseUnderline = true;
		this.IncTempoBtn.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.hbox1.Add (this.IncTempoBtn);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.IncTempoBtn]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.DecTempoBtn = new global::Gtk.Button ();
		this.DecTempoBtn.CanFocus = true;
		this.DecTempoBtn.Name = "DecTempoBtn";
		this.DecTempoBtn.UseUnderline = true;
		this.DecTempoBtn.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.hbox1.Add (this.DecTempoBtn);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.DecTempoBtn]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UpperMeterCB = global::Gtk.ComboBox.NewText ();
		this.UpperMeterCB.Name = "UpperMeterCB";
		this.hbox2.Add (this.UpperMeterCB);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.UpperMeterCB]));
		w7.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.LowerMeterCB = global::Gtk.ComboBox.NewText ();
		this.LowerMeterCB.Name = "LowerMeterCB";
		this.hbox2.Add (this.LowerMeterCB);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LowerMeterCB]));
		w8.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 4;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
		this.StartBtn.Pressed += new global::System.EventHandler (this.OnStartBtnPressed);
		this.StopBtn.Pressed += new global::System.EventHandler (this.OnStopBtnPressed);
		this.ResetBtn.Pressed += new global::System.EventHandler (this.OnResetBtnPressed);
		this.IncTempoBtn.Pressed += new global::System.EventHandler (this.OnIncTempoBtnPressed);
		this.DecTempoBtn.Pressed += new global::System.EventHandler (this.OnDecTempoBtnPressed);
	}
}
