#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeatPlannerAndroid.Resource", IsApplication=true)]

namespace BeatPlannerAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int lowerMeterValues = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int upperMeterValues = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int bpm = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int lowerMeter = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int reps = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int upperMeter = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int bpmSeekBar = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int bpmText = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int dec_tempo = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int inc_tempo = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout2 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int lowerMeter = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int meterLayout = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int startBtn = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int stopBtn = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int tempoLayout = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int tempo_inc_dec_layout = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textView2 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int trackRoot = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int upperMeter = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Metro = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Track = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int llfclave = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int llfclave_low = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SequenceView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 2
			public const int SequenceView_bpm = 2;
			
			// aapt resource value: 1
			public const int SequenceView_lowerMeter = 1;
			
			// aapt resource value: 3
			public const int SequenceView_reps = 3;
			
			// aapt resource value: 0
			public const int SequenceView_upperMeter = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
